moonqueen = {}
---@return table
moonqueen.build = function()
	local theme = {
		Normal = {fg = "#DDCDFE", bg = "#241A37"},
		MiniStatuslineFilename = {link = "Normal"},
		StatusLine = {link = "Normal"},
		["@boolean"] = {link = "Boolean"},
		Character = {fg = "#B6CA68"},
		Boolean = {link = "Character"},
		Float = {link = "Character"},
		Number = {link = "Character"},
		["@character"] = {link = "Character"},
		ColorColumn = {bg = "#433168"},
		Comment = {fg = "#736490"},
		LspCodeLens = {link = "Comment"},
		LspCodeLensSeparator = {link = "Comment"},
		["@comment"] = {link = "Comment"},
		["@text.literal"] = {link = "Comment"},
		Conceal = {fg = "#736490"},
		["@conditional"] = {link = "Conditional"},
		Constant = {fg = "#F5AB00"},
		["@constant"] = {link = "Constant"},
		CurSearch = {fg = "#362753", bg = "#FFD470"},
		IncSearch = {link = "CurSearch"},
		Cursor = {fg = "#241A37", bg = "#DDCDFE"},
		CursorIM = {link = "Cursor"},
		WildMenu = {link = "Cursor"},
		lCursor = {link = "Cursor"},
		CursorColumn = {bg = "#362753"},
		CursorLine = {link = "CursorColumn"},
		CursorLineNr = {fg = "#F7A1D5", bg = "#362753", bold = true},
		["@debug"] = {link = "Debug"},
		["@constant.macro"] = {link = "Define"},
		["@define"] = {link = "Define"},
		Delimiter = {fg = "#E873B9"},
		["@punctuation"] = {link = "Delimiter"},
		DiagnosticError = {fg = "#EF434C"},
		DiagnosticFloatingError = {link = "DiagnosticError"},
		DiagnosticSignError = {link = "DiagnosticError"},
		DiagnosticVirtualTextError = {link = "DiagnosticError"},
		DiagnosticHint = {fg = "#E873B9"},
		DiagnosticFloatingHint = {link = "DiagnosticHint"},
		DiagnosticSignHint = {link = "DiagnosticHint"},
		DiagnosticVirtualTextHint = {link = "DiagnosticHint"},
		DiagnosticInfo = {fg = "#7CACF4"},
		DiagnosticFloatingInfo = {link = "DiagnosticInfo"},
		DiagnosticSignInfo = {link = "DiagnosticInfo"},
		DiagnosticVirtualTextInfo = {link = "DiagnosticInfo"},
		DiagnosticOk = {fg = "#6CA522"},
		DiagnosticFloatingOk = {link = "DiagnosticOk"},
		DiagnosticSignOk = {link = "DiagnosticOk"},
		DiagnosticVirtualTextOk = {link = "DiagnosticOk"},
		DiagnosticUnderlineError = {fg = "#EF434C", underline = true},
		DiagnosticUnderlineHint = {fg = "#E873B9", underline = true},
		DiagnosticUnderlineInfo = {fg = "#7CACF4", underline = true},
		DiagnosticUnderlineOk = {fg = "#6CA522", underline = true},
		DiagnosticUnderlineWarn = {fg = "#FFD470", underline = true},
		DiagnosticWarn = {fg = "#FFD470"},
		DiagnosticFloatingWarn = {link = "DiagnosticWarn"},
		DiagnosticSignWarn = {link = "DiagnosticWarn"},
		DiagnosticVirtualTextWarn = {link = "DiagnosticWarn"},
		DiffAdd = {fg = "#F1EBFF", bg = "#3B7D70", bold = true},
		DiffChange = {fg = "#DDCDFE", bg = "#2246D3", bold = true},
		DiffDelete = {fg = "#DDCDFE", bg = "#93255C", bold = true},
		DiffText = {fg = "#E873B9", bold = true, italic = true},
		Directory = {fg = "#8877F8"},
		EndOfBuffer = {fg = "#736490"},
		Error = {fg = "#241A37", bg = "#EF434C"},
		ErrorMsg = {fg = "#B5407A", bg = "#362753"},
		["@exception"] = {link = "Exception"},
		["@float"] = {link = "Float"},
		FloatTitle = {fg = "#DDCDFE", bold = true},
		FoldColumn = {fg = "#513B7D"},
		CursorLineFold = {link = "FoldColumn"},
		CursorLineSign = {link = "FoldColumn"},
		Folded = {fg = "#DDCDFE", bg = "#1F1731"},
		Function = {fg = "#7CACF4"},
		["@function"] = {link = "Function"},
		["@method"] = {link = "Function"},
		GitSignsAdd = {fg = "#40B59E"},
		GitSignsChange = {fg = "#506DE2"},
		GitSignsDelete = {fg = "#B5407A"},
		Identifier = {fg = "#8877F8"},
		["@field"] = {link = "Identifier"},
		["@namespace"] = {link = "Identifier"},
		["@parameter"] = {link = "Identifier"},
		["@property"] = {link = "Identifier"},
		["@text.reference"] = {link = "Identifier"},
		["@variable"] = {link = "Identifier"},
		Ignore = {fg = "#9181B1"},
		Search = {link = "IncSearch"},
		["@include"] = {link = "Include"},
		["@keyword"] = {link = "Keyword"},
		["@label"] = {link = "Label"},
		LineNr = {fg = "#9F91FD", bg = "#4A3B7D"},
		LineNrAbove = {link = "LineNr"},
		LineNrBelow = {link = "LineNr"},
		["@function.macro"] = {link = "Macro"},
		["@macro"] = {link = "Macro"},
		MatchParen = {fg = "#F7A1D5", bg = "#4A3B7D", bold = true},
		MiniDiffSignAdd = {fg = "#40B59E", italic = true},
		MiniDiffSignChange = {fg = "#506DE2", italic = true},
		MiniDiffSignDelete = {fg = "#B5407A", italic = true},
		MiniStatuslineDevinfo = {fg = "#DDCDFE", bg = "#362753"},
		MiniStatuslineFileinfo = {link = "MiniStatuslineDevinfo"},
		MiniStatuslineInactive = {fg = "#9C84EB", bg = "#1B142A"},
		MiniStatuslineModeCommand = {fg = "#433168", bg = "#F7A1D5"},
		MiniStatuslineModeInsert = {fg = "#433168", bg = "#DDCDFE"},
		MiniStatuslineModeNormal = {fg = "#DDCDFE", bg = "#634EA6"},
		MiniStatuslineModeOther = {fg = "#362753", bg = "#B6CA68"},
		MiniStatuslineModeReplace = {fg = "#433168", bg = "#FC737A"},
		MiniStatuslineModeVisual = {fg = "#362753", bg = "#FFD470"},
		MiniTablineModifiedCurrent = {fg = "#241A37", bg = "#9C84EB", bold = true, italic = true},
		MiniTablineModifiedHidden = {fg = "#736490", bg = "#1F1731", bold = true},
		MiniTablineModifiedVisible = {fg = "#9F91FD", bg = "#362753", bold = true},
		MiniTablineVisible = {fg = "#9F91FD", bg = "#362753"},
		ModeMsg = {fg = "#DDCDFE", bold = true},
		MoreMsg = {fg = "#513B7D"},
		MsgArea = {fg = "#DDCDFE"},
		MsgSeparator = {fg = "#241A37", bg = "#9181B1"},
		NonText = {fg = "#736490"},
		NormalFloat = {fg = "#9181B1", bg = "#1F1731"},
		FloatBorder = {link = "NormalFloat"},
		NormalNC = {fg = "#736490"},
		["@number"] = {link = "Number"},
		Operator = {fg = "#FFD470"},
		["@operator"] = {link = "Operator"},
		Pmenu = {fg = "#DDCDFE", bg = "#1F1731"},
		PmenuExtra = {link = "Pmenu"},
		PmenuKind = {link = "Pmenu"},
		PmenuSbar = {link = "Pmenu"},
		PmenuSel = {fg = "#1F1731", bg = "#DDCDFE"},
		PmenuExtraSel = {link = "PmenuSel"},
		PmenuKindSel = {link = "PmenuSel"},
		PmenuThumb = {fg = "#F1EBFF", bg = "#736490"},
		PreProc = {fg = "#9F91FD"},
		Define = {link = "PreProc"},
		Include = {link = "PreProc"},
		Macro = {link = "PreProc"},
		PreCondit = {link = "PreProc"},
		["@preproc"] = {link = "PreProc"},
		Question = {fg = "#F7A1D5"},
		QuickFixLine = {link = "Question"},
		RenderMarkdownH1Bg = {fg = "#241A37", bg = "#E873B9"},
		RenderMarkdownH2Bg = {fg = "#241A37", bg = "#508AE2"},
		RenderMarkdownH3Bg = {fg = "#241A37", bg = "#F5AB00"},
		RenderMarkdownH4Bg = {fg = "#241A37", bg = "#EF434C"},
		RenderMarkdownH5Bg = {fg = "#241A37", bg = "#6CA522"},
		RenderMarkdownH6Bg = {fg = "#241A37", bg = "#8877F8"},
		["@repeat"] = {link = "Repeat"},
		SignColumn = {bg = "#312753"},
		Special = {fg = "#F7A1D5"},
		Debug = {link = "Special"},
		SpecialComment = {link = "Special"},
		Tag = {link = "Special"},
		["@constant.builtin"] = {link = "Special"},
		["@constructor"] = {link = "Special"},
		["@function.builtin"] = {link = "Special"},
		SpecialChar = {fg = "#40B59E"},
		["@character.special"] = {link = "SpecialChar"},
		["@string.escape"] = {link = "SpecialChar"},
		["@string.special"] = {link = "SpecialChar"},
		SpecialKey = {fg = "#9181B1"},
		SpellBad = {fg = "#EF434C", undercurl = true},
		SpellCap = {fg = "#7CACF4", undercurl = true},
		SpellLocal = {fg = "#B6CA68", undercurl = true},
		SpellRare = {fg = "#F5AB00", undercurl = true},
		Statement = {fg = "#FC737A", bold = true},
		Conditional = {link = "Statement"},
		Exception = {link = "Statement"},
		Keyword = {link = "Statement"},
		Label = {link = "Statement"},
		Repeat = {link = "Statement"},
		StatusLineNC = {bg = "#1B142A"},
		["@storageclass"] = {link = "StorageClass"},
		String = {fg = "#9F91FD"},
		["@string"] = {link = "String"},
		["@structure"] = {link = "Structure"},
		Substitute = {fg = "#433168", bg = "#F5AB00"},
		TabLine = {fg = "#736490", bg = "#1F1731"},
		MiniTablineHidden = {link = "TabLine"},
		TabLineFill = {bg = "#1B142A"},
		MiniTablineFill = {link = "TabLineFill"},
		TabLineSel = {fg = "#241A37", bg = "#9C84EB", italic = true},
		MiniTablineCurrent = {link = "TabLineSel"},
		["@tag"] = {link = "Tag"},
		TermCursor = {fg = "#241A37", bg = "#9181B1"},
		TermCursorNC = {fg = "#9181B1"},
		Title = {bold = true},
		["@text.title"] = {link = "Title"},
		Todo = {bold = true},
		["@text.todo"] = {link = "Todo"},
		TroubleIndent = {fg = "#9C84EB", bg = "#1F1731"},
		TroublePos = {fg = "#9C84EB", bg = "#1F1731"},
		Type = {fg = "#508AE2"},
		StorageClass = {link = "Type"},
		Structure = {link = "Type"},
		Typedef = {link = "Type"},
		["@type"] = {link = "Type"},
		["@type.definition"] = {link = "Typedef"},
		Underlined = {underline = true},
		["@text.underline"] = {link = "Underlined"},
		["@text.uri"] = {link = "Underlined"},
		VertSplit = {fg = "#362753"},
		Winseparator = {link = "VertSplit"},
		Visual = {fg = "#241A37", bg = "#9C84EB"},
		LspReferenceRead = {link = "Visual"},
		LspReferenceText = {link = "Visual"},
		LspReferenceWrite = {link = "Visual"},
		LspSignatureActiveParameter = {link = "Visual"},
		VisualNOS = {fg = "#DDCDFE", bg = "#4A3B7D"},
		WarningMsg = {fg = "#9F91FD"},
		Whitespace = {fg = "#513B7D"},
		WinBar = {bg = "#1B142A", bold = true},
		WinBarNC = {bg = "#1B142A"},
	}
	local opts = require("moonqueen").opts
	if opts.transparent then
		theme["Normal"].bg = "none"
		theme["StatusLine"].bg = "none"
	end
	if opts.overrides ~= false then
		theme = vim.tbl_deep_extend("force", theme, opts.overrides)
	end
	return theme
end
return moonqueen
