moonqueen = {}
---@return table
moonqueen.build = function()
	local theme = {
		Normal = {fg = "#CCBEEF", bg = "#0D0A15"},
		Boolean = {fg = "#6CA522"},
		Character = {fg = "#F8303A"},
		ColorColumn = {bg = "#1A142A"},
		Comment = {fg = "#72688D", italic = true},
		Conceal = {fg = "#FD8BD9", bg = "#0D0A15"},
		Conditional = {fg = "#AB96F8"},
		Constant = {fg = "#6CA522"},
		CurSearch = {fg = "#1A142A", bg = "#6CA522"},
		Cursor = {fg = "#0D0A15", bg = "#CCBEEF"},
		CursorColumn = {link = "Cursor"},
		TermCursor = {link = "Cursor"},
		CursorLine = {bg = "#271D3E"},
		CursorLineNr = {fg = "#FD8BD9", bg = "#1A142A", bold = true},
		Debug = {fg = "#F8303A"},
		Define = {fg = "#AB96F8"},
		Delimiter = {fg = "#FEBEEA"},
		DiagnosticError = {fg = "#F8303A"},
		DiagnosticHint = {fg = "#72688D"},
		DiagnosticInfo = {fg = "#CCBEEF"},
		DiagnosticOk = {fg = "#8566F5"},
		DiagnosticWarn = {fg = "#6CA522"},
		DiffAdd = {fg = "#1A142A", bg = "#4C8FE6"},
		DiffChange = {fg = "#DFD6F5", bg = "#342753"},
		DiffDelete = {fg = "#1A142A", bg = "#F8303A"},
		DiffText = {fg = "#1A142A", bg = "#FD8BD9"},
		Directory = {fg = "#FD8BD9"},
		EndOfBuffer = {fg = "#FD8BD9"},
		Error = {fg = "#F8303A"},
		ErrorMsg = {fg = "#F8303A"},
		Exception = {fg = "#F8303A"},
		Float = {fg = "#6CA522"},
		FoldColumn = {fg = "#8566F5", bg = "#1A142A"},
		CursorLineFold = {link = "FoldColumn"},
		Folded = {fg = "#72688D", bg = "#1A142A"},
		SignColumn = {link = "Folded"},
		Function = {fg = "#FD8BD9"},
		Identifier = {fg = "#F8303A"},
		IncSearch = {fg = "#1A142A", bg = "#6CA522"},
		Include = {fg = "#FD8BD9"},
		Keyword = {fg = "#AB96F8"},
		Label = {fg = "#FBE918"},
		LineNr = {fg = "#1A142A", bg = "#8566F5"},
		Macro = {fg = "#F8303A"},
		MatchParen = {bg = "#342753"},
		ModeMsg = {fg = "#4C8FE6"},
		MoreMsg = {link = "ModeMsg"},
		NonText = {fg = "#72688D"},
		Number = {fg = "#6CA522"},
		Operator = {fg = "#CCBEEF"},
		Pmenu = {fg = "#CCBEEF", bg = "#1A142A"},
		PmenuExtra = {link = "Pmenu"},
		PmenuKind = {link = "Pmenu"},
		PmenuSbar = {fg = "#271D3E"},
		PmenuSel = {fg = "#1A142A", bg = "#CCBEEF"},
		PmenuExtraSel = {link = "PmenuSel"},
		PmenuKindSel = {link = "PmenuSel"},
		PmenuThumb = {fg = "#342753"},
		PreCondit = {fg = "#AB96F8"},
		PreProc = {fg = "#FBE918"},
		Question = {fg = "#AB96F8"},
		QuickFixLine = {fg = "#AB96F8"},
		Repeat = {fg = "#FBE918"},
		Search = {fg = "#271D3E", bg = "#8566F5"},
		CursorLineSign = {link = "SignColumn"},
		Special = {fg = "#8566F5"},
		SpecialChar = {fg = "#FEBEEA"},
		SpecialComment = {fg = "#AB96F8"},
		SpellBad = {fg = "#F8303A", undercurl = true},
		SpellCap = {fg = "#8566F5", undercurl = true},
		SpellLocal = {fg = "#FD8BD9", undercurl = true},
		SpellRare = {fg = "#AB96F8", undercurl = true},
		Statement = {fg = "#F8303A"},
		StatusLine = {fg = "#928AA8", bg = "#1A142A", italic = true},
		StatusLineNC = {fg = "#72688D", bg = "#0D0A15"},
		StorageClass = {fg = "#FBE918"},
		String = {fg = "#4C8FE6"},
		Structure = {fg = "#AB96F8"},
		Substitute = {fg = "#1A142A", bg = "#FBE918"},
		TabLine = {fg = "#72688D", bg = "#271D3E"},
		TabLineFill = {link = "TabLine"},
		TabLineSel = {fg = "#4C8FE6", bg = "#1A142A"},
		Tag = {fg = "#FBE918"},
		TermCursorNC = {fg = "#CCBEEF", bg = "#72688D"},
		Title = {fg = "#FD8BD9"},
		Todo = {fg = "#FBE918", bg = "#1A142A"},
		Type = {fg = "#FBE918"},
		Typedef = {fg = "#FBE918"},
		Underlined = {fg = "#F8303A", underline = true},
		VertSplit = {fg = "#8566F5"},
		Winseparator = {link = "VertSplit"},
		Visual = {fg = "#DFD6F5", bg = "#342753"},
		VisualNOS = {fg = "#F8303A"},
		WarningMsg = {fg = "#F8303A"},
		WildMenu = {fg = "#F8303A", bg = "#DFD6F5"},
	}
	local opts = require("moonqueen").opts
	if opts.transparent then
		theme["Normal"].bg = "none"
		theme["StatusLine"].bg = "none"
	end
	if opts.overrides ~= false then
		theme = vim.tbl_deep_extend("force", theme, opts.overrides)
	end
	return theme
end
return moonqueen
