S = {}
---@return table
S.build = function()
  local theme = {
Normal = {fg = "#E1D9F2", bg = "#1B1429"},
["@boolean"] = {link = "Boolean"},
["@character"] = {link = "Character"},
ColorColumn = {bg = "#291E3E"},
Comment = {fg = "#9180B3", italic = true},
["@comment"] = {link = "Comment"},
["@lsp.type.comment"] = {link = "Comment"},
Conceal = {fg = "#473D5C"},
["@keyword.conditional"] = {link = "Conditional"},
Constant = {fg = "#EBB447"},
Boolean = {link = "Constant"},
Character = {link = "Constant"},
Float = {link = "Constant"},
Number = {link = "Constant"},
String = {link = "Constant"},
["@constant"] = {link = "Constant"},
["@lsp.type.enumMember"] = {link = "Constant"},
CurSearch = {fg = "#1B1429", bg = "#EBB447"},
IncSearch = {link = "CurSearch"},
Cursor = {fg = "#1B1429", bg = "#E1D9F2"},
CursorIM = {link = "Cursor"},
lCursor = {link = "Cursor"},
CursorColumn = {bg = "#362853"},
CursorLine = {bg = "#362853"},
CursorLineNr = {fg = "#E1D9F2", bold = true},
["@constant.macro"] = {link = "Define"},
Delimiter = {fg = "#E1D9F2"},
DiagnosticDeprecated = {fg = "#473D5C", strikethrough = true},
DiagnosticError = {fg = "#D65C5C"},
DiagnosticFloatingError = {link = "DiagnosticError"},
DiagnosticSignError = {link = "DiagnosticError"},
DiagnosticHint = {fg = "#DB70B8"},
DiagnosticFloatingHint = {link = "DiagnosticHint"},
DiagnosticSignHint = {link = "DiagnosticHint"},
DiagnosticInfo = {fg = "#5CADD6"},
DiagnosticFloatingInfo = {link = "DiagnosticInfo"},
DiagnosticSignInfo = {link = "DiagnosticInfo"},
DiagnosticOk = {fg = "#85D65C"},
DiagnosticFloatingOk = {link = "DiagnosticOk"},
DiagnosticSignOk = {link = "DiagnosticOk"},
DiagnosticUnderlineError = {fg = "#D65C5C", undercurl = true},
DiagnosticUnderlineHint = {fg = "#DB70B8", undercurl = true},
DiagnosticUnderlineInfo = {fg = "#5CADD6", undercurl = true},
DiagnosticUnderlineOk = {fg = "#85D65C", undercurl = true},
DiagnosticUnderlineWarn = {fg = "#EBB447", undercurl = true},
DiagnosticVirtualTextError = {fg = "#D65C5C", italic = true},
DiagnosticVirtualTextHint = {fg = "#DB70B8", italic = true},
DiagnosticVirtualTextInfo = {fg = "#5CADD6", italic = true},
DiagnosticVirtualTextOk = {fg = "#85D65C", italic = true},
DiagnosticVirtualTextWarn = {fg = "#EBB447", italic = true},
DiagnosticWarn = {fg = "#EBB447"},
DiagnosticFloatingWarn = {link = "DiagnosticWarn"},
DiagnosticSignWarn = {link = "DiagnosticWarn"},
DiffAdd = {fg = "#1B1429", bg = "#85D65C"},
DiffChange = {fg = "#1B1429", bg = "#EBB447"},
DiffDelete = {fg = "#D65C5C", bold = true},
DiffText = {fg = "#1B1429", bg = "#5CADD6"},
Directory = {fg = "#5CADD6"},
EndOfBuffer = {fg = "#473D5C"},
Error = {fg = "#1B1429", bg = "#D65C5C"},
ErrorMsg = {fg = "#D65C5C", bold = true},
["@keyword.exception"] = {link = "Exception"},
["@number.float"] = {link = "Float"},
FloatBorder = {fg = "#473D5C", bg = "#291E3E"},
FloatFooter = {link = "FloatBorder"},
FloatTitle = {fg = "#DB70B8", bg = "#291E3E", bold = true},
FoldColumn = {fg = "#453762", bg = "#291E3E"},
Folded = {fg = "#9180B3", bg = "#171122"},
Function = {fg = "#DB70B8"},
["@function"] = {link = "Function"},
["@function.method"] = {link = "Function"},
["@lsp.type.function"] = {link = "Function"},
["@lsp.type.method"] = {link = "Function"},
Identifier = {fg = "#8F7DE8"},
Ignore = {fg = "#473D5C"},
["@keyword.import"] = {link = "Include"},
["@keyword"] = {link = "Keyword"},
["@lsp.type.keyword"] = {link = "Keyword"},
LineNr = {fg = "#473D5C"},
LineNrAbove = {link = "LineNr"},
LineNrBelow = {link = "LineNr"},
["@function.macro"] = {link = "Macro"},
["@lsp.type.macro"] = {link = "Macro"},
MatchParen = {bg = "#453762", bold = true},
MiniDiffSignAdd = {fg = "#85D65C", italic = true},
MiniDiffSignChange = {fg = "#EBB447", italic = true},
MiniDiffSignDelete = {fg = "#D65C5C", italic = true},
MiniStatuslineDevinfo = {fg = "#E1D9F2", bg = "#362853"},
MiniStatuslineFileinfo = {link = "MiniStatuslineDevinfo"},
MiniStatuslineFilename = {fg = "#9180B3", bg = "#291E3E"},
MiniStatuslineInactive = {fg = "#473D5C", bg = "#1B1429"},
MiniStatuslineModeCommand = {fg = "#1B1429", bg = "#DB70B8", bold = true},
MiniStatuslineModeInsert = {fg = "#1B1429", bg = "#E1D9F2", bold = true},
MiniStatuslineModeNormal = {fg = "#E1D9F2", bg = "#453762", bold = true},
MiniStatuslineModeOther = {fg = "#1B1429", bg = "#85D65C", bold = true},
MiniStatuslineModeReplace = {fg = "#1B1429", bg = "#D65C5C", bold = true},
MiniStatuslineModeVisual = {fg = "#1B1429", bg = "#8F7DE8", bold = true},
MiniTablineVisible = {fg = "#EBB447", bg = "#291E3E"},
ModeMsg = {fg = "#E1D9F2", bold = true},
MoreMsg = {fg = "#85D65C"},
MsgArea = {fg = "#E1D9F2"},
MsgSeparator = {fg = "#362853"},
NonText = {fg = "#473D5C"},
NormalFloat = {fg = "#E1D9F2", bg = "#291E3E"},
NormalNC = {fg = "#9180B3", bg = "#1B1429"},
["@lsp.type.number"] = {link = "Number"},
["@number"] = {link = "Number"},
Operator = {fg = "#E1D9F2"},
["@lsp.type.operator"] = {link = "Operator"},
["@operator"] = {link = "Operator"},
Pmenu = {fg = "#E1D9F2", bg = "#291E3E"},
PmenuExtra = {fg = "#473D5C", bg = "#291E3E"},
PmenuExtraSel = {fg = "#9180B3", bg = "#362853"},
PmenuKind = {fg = "#8F7DE8", bg = "#291E3E"},
PmenuKindSel = {fg = "#8F7DE8", bg = "#362853", bold = true},
PmenuMatch = {fg = "#DB70B8", bold = true},
PmenuMatchSel = {fg = "#DB70B8", bold = true, underline = true},
PmenuSbar = {bg = "#362853"},
PmenuSel = {fg = "#DB70B8", bg = "#362853", bold = true},
PmenuThumb = {bg = "#453762"},
PreProc = {fg = "#5CADD6"},
Define = {link = "PreProc"},
Include = {link = "PreProc"},
Macro = {link = "PreProc"},
PreCondit = {link = "PreProc"},
["@keyword.directive"] = {link = "PreProc"},
Question = {fg = "#5CADD6"},
QuickFixLine = {bg = "#362853", bold = true},
["@keyword.repeat"] = {link = "Repeat"},
Search = {fg = "#EBB447", bg = "#2E2442"},
SignColumn = {bg = "#1B1429"},
Special = {fg = "#8F7DE8"},
Debug = {link = "Special"},
SpecialChar = {link = "Special"},
Tag = {link = "Special"},
["@character.special"] = {link = "SpecialChar"},
SpecialComment = {fg = "#9180B3", bold = true},
SpecialKey = {fg = "#473D5C"},
SpellBad = {fg = "#D65C5C", undercurl = true},
SpellCap = {fg = "#EBB447", undercurl = true},
SpellLocal = {fg = "#85D65C", undercurl = true},
SpellRare = {fg = "#5CADD6", undercurl = true},
Statement = {fg = "#5CADD6", bold = true},
Conditional = {link = "Statement"},
Exception = {link = "Statement"},
Keyword = {link = "Statement"},
Label = {link = "Statement"},
Repeat = {link = "Statement"},
StatusLine = {fg = "#E1D9F2", bg = "#362853"},
StatusLineNC = {fg = "#473D5C", bg = "#291E3E"},
["@lsp.type.string"] = {link = "String"},
["@string"] = {link = "String"},
["@lsp.type.struct"] = {link = "Structure"},
Substitute = {fg = "#1B1429", bg = "#5CADD6"},
TabLine = {fg = "#473D5C", bg = "#291E3E"},
MiniTablineHidden = {link = "TabLine"},
TabLineFill = {bg = "#1B1429"},
TabLineSel = {fg = "#DB70B8", bg = "#362853", bold = true},
MiniTablineCurrent = {link = "TabLineSel"},
TermCursor = {fg = "#1B1429", bg = "#DB70B8"},
TermCursorNC = {fg = "#1B1429", bg = "#9180B3"},
Title = {fg = "#DB70B8", bold = true},
Todo = {fg = "#EBB447", bold = true},
TroubleIndent = {fg = "#9180B3", bg = "#291E3E"},
TroublePos = {fg = "#9180B3", bg = "#291E3E"},
Type = {fg = "#85D65C"},
StorageClass = {link = "Type"},
Structure = {link = "Type"},
["@lsp.type.class"] = {link = "Type"},
["@lsp.type.enum"] = {link = "Type"},
["@lsp.type.type"] = {link = "Type"},
["@type"] = {link = "Type"},
["@variable.parameter"] = {link = "Type"},
Typedef = {fg = "#85D65C", italic = true},
["@lsp.type.interface"] = {link = "Typedef"},
["@lsp.type.typeParameter"] = {link = "Typedef"},
["@type.definition"] = {link = "Typedef"},
Underlined = {underline = true},
VertSplit = {fg = "#291E3E"},
Visual = {bg = "#453762"},
VisualNOS = {link = "Visual"},
WarningMsg = {fg = "#EBB447"},
Whitespace = {fg = "#362853"},
WildMenu = {fg = "#1B1429", bg = "#E1D9F2"},
WinBar = {fg = "#9180B3", bg = "#2E2442"},
WinBarNC = {fg = "#473D5C", bg = "#2E2442"},
WinSeparator = {fg = "#291E3E"},
markdownH1 = {fg = "#DB70B8", bold = true},
markdownH1Delimiter = {link = "markdownH1"},
markdownH2 = {fg = "#5CADD6", bold = true},
markdownH2Delimiter = {link = "markdownH2"},
markdownH3 = {fg = "#D65C5C", bold = true},
markdownH3Delimiter = {link = "markdownH3"},
markdownH4 = {fg = "#85D65C", bold = true},
markdownH4Delimiter = {link = "markdownH4"},
markdownH5 = {fg = "#EBB447", bold = true},
markdownH5Delimiter = {link = "markdownH5"},
markdownH6 = {fg = "#8F7DE8", bold = true},
markdownH6Delimiter = {link = "markdownH6"},
["@attribute"] = {fg = "#EBB447"},
["@attribute.builtin"] = {fg = "#EBB447", bold = true, italic = true},
["@comment.documentation"] = {fg = "#9180B3", italic = true},
["@comment.error"] = {fg = "#D65C5C", bold = true},
["@comment.note"] = {fg = "#5CADD6", bold = true},
["@comment.todo"] = {fg = "#EBB447", bold = true},
["@comment.warning"] = {fg = "#EBB447", bold = true},
["@constant.builtin"] = {fg = "#EBB447", bold = true, italic = true},
["@constructor"] = {fg = "#DB70B8"},
["@diff.delta"] = {fg = "#EBB447"},
GitSignsChange = {link = "@diff.delta"},
["@diff.minus"] = {fg = "#D65C5C"},
GitSignsDelete = {link = "@diff.minus"},
["@diff.plus"] = {fg = "#85D65C"},
GitSignsAdd = {link = "@diff.plus"},
["@function.builtin"] = {fg = "#8F7DE8", bold = true, italic = true},
["@keyword.function"] = {fg = "#5CADD6", italic = true},
["@keyword.operator"] = {fg = "#5CADD6"},
["@keyword.return"] = {fg = "#D65C5C", italic = true},
["@label"] = {fg = "#5CADD6"},
["@lsp.mod.defaultLibrary"] = {italic = true},
["@lsp.mod.deprecated"] = {fg = "#473D5C", strikethrough = true},
["@lsp.mod.readonly"] = {italic = true},
["@lsp.type.decorator"] = {fg = "#EBB447"},
["@lsp.type.namespace"] = {fg = "#E1D9F2", italic = true},
["@lsp.type.parameter"] = {fg = "#8F7DE8", italic = true},
["@lsp.type.property"] = {fg = "#E1D9F2"},
["@lsp.type.variable"] = {fg = "#E1D9F2"},
["@markup.heading"] = {fg = "#DB70B8", bold = true},
["@markup.heading.1"] = {fg = "#DB70B8", bg = "#3C2A36", bold = true},
RenderMarkdownH1Bg = {link = "@markup.heading.1"},
["@markup.heading.2"] = {fg = "#5CADD6", bg = "#263136", bold = true},
RenderMarkdownH2Bg = {link = "@markup.heading.2"},
["@markup.heading.3"] = {fg = "#D65C5C", bg = "#362626", bold = true},
RenderMarkdownH3Bg = {link = "@markup.heading.3"},
["@markup.heading.4"] = {fg = "#85D65C", bg = "#2B3626", bold = true},
RenderMarkdownH4Bg = {link = "@markup.heading.4"},
["@markup.heading.5"] = {fg = "#EBB447", bg = "#393223", bold = true},
RenderMarkdownH5Bg = {link = "@markup.heading.5"},
["@markup.heading.6"] = {fg = "#8F7DE8", bg = "#2E2A41", bold = true},
RenderMarkdownH6Bg = {link = "@markup.heading.6"},
["@markup.italic"] = {italic = true},
["@markup.link"] = {fg = "#5CADD6", underline = true},
["@markup.link.label"] = {fg = "#DB70B8"},
["@markup.link.url"] = {fg = "#5CADD6", italic = true, underline = true},
["@markup.list"] = {fg = "#EBB447"},
["@markup.quote"] = {fg = "#9180B3", italic = true},
["@markup.raw"] = {fg = "#85D65C"},
["@markup.raw.block"] = {fg = "#85D65C"},
["@markup.strikethrough"] = {fg = "#473D5C", strikethrough = true},
["@markup.strong"] = {bold = true},
["@module"] = {fg = "#EBB447"},
["@module.builtin"] = {fg = "#EBB447", bold = true, italic = true},
["@property"] = {fg = "#DB70B8", italic = true},
["@punctuation.bracket"] = {fg = "#E1D9F2"},
["@punctuation.delimiter"] = {fg = "#473D5C"},
["@punctuation.special"] = {fg = "#DB70B8"},
["@string.escape"] = {fg = "#DB70B8"},
["@string.regexp"] = {fg = "#EBB447"},
["@string.special"] = {fg = "#DB70B8"},
["@string.special.url"] = {fg = "#5CADD6", underline = true},
["@tag"] = {fg = "#5CADD6"},
["@tag.attribute"] = {fg = "#EBB447"},
["@tag.builtin"] = {fg = "#5CADD6", bold = true, italic = true},
["@tag.delimiter"] = {fg = "#473D5C"},
["@type.builtin"] = {fg = "#85D65C", bold = true, italic = true},
["@variable"] = {fg = "#E1D9F2", italic = true},
["@variable.builtin"] = {fg = "#DB70B8", bold = true, italic = true},
["@variable.member"] = {fg = "#E1D9F2"},
  }
  return theme
end
return S
