[colors]
foreground = "#dbd6f0"
background = "#0c0916"
cursor_bg = "#dbd6f0"
cursor_border = "#dbd6f0"
cursor_fg = "#0c0916"
selection_bg = "#3e2b6e"
selection_fg = "#dbd6f0"
split = "#221c40"
compose_cursor = "#fcb54a"
scrollbar_thumb = "#16122b"

ansi = ["#22163b", "#fd8bd9", "#4d8fe6", "#f8303a", "#6ca522", "#fbe918", "#8566f5", "#cfc5e7"]
brights = ["#392b5a", "#febeea", "#79abec", "#f96269", "#99d945", "#fdf27c", "#ab96f8", "#e1dbf0"]

[colors.tab_bar]
inactive_tab_edge = "#16122b"
background = "#0c0916"

[colors.tab_bar.active_tab]
fg_color = "#dbd6f0"
bg_color = "#221c40"

[colors.tab_bar.inactive_tab]
fg_color = "#726a90"
bg_color = "#16122b"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#a49cc4"
bg_color = "#16122b"
intensity = "Bold"

[colors.tab_bar.new_tab_hover]
fg_color = "#8566f5"
bg_color = "#0c0916"
intensity = "Bold"

[colors.tab_bar.new_tab]
fg_color = "#ab96f8"
bg_color = "#0c0916"

[metadata]
aliases = []
author = "spica"
name = "moonqueen"
origin_url = "https://codeberg.org/spica/moonqueen.nvim"
