# -----------------------------------------------------------------------------
# Moon Queen Alacritty Colors
# Theme: Moon Queen
# Upstream: https://codeberg.org/spica/moonqueen.nvim/src/branch/dev/extras/alacritty/moonqueen.toml
# -----------------------------------------------------------------------------

[colors.primary]
background = '#0d0a15'
foreground = '#dbd6f0'

[colors.cursor]
cursor = '#dbd6f0'
text = '#0d0a15'

[colors.normal]
black = '#21163b'
red = '#fd8bd9'
green = '#4d8fe6'
yellow = '#f8303a'
blue = '#6ca522'
magenta = '#fbe918'
cyan = '#8566f5'
white = '#cfc5e7'

[colors.bright]
black = '#392b5a'
red = '#febeea'
green = '#79abec'
yellow = '#f96269'
blue = '#99d945'
magenta = '#fdf27c'
cyan = '#ab96f8'
white = '#dbd6f0'
