# -----------------------------------------------------------------------------
# Moonqueen Alacritty Colors
# Theme: Moon Queen
# Upstream: https://codeberg.org/spica/moonqueen.nvim/src/branch/main/extras/alacritty/moonqueen.toml
# -----------------------------------------------------------------------------

# Default colors
[colors.primary]
background = '#241a37'
foreground = '#d0c3ea'

#[colors.cursor]
#cursor = '#d0c3ea'
#text = '#241a37'

# Normal colors
[colors.normal]
black = '#362753'
red = '#ef434c'
green = '#6ca522'
yellow = '#ffc233'
blue = '#508ae2'
magenta = '#8d77f8'
cyan = '#e873d1'
white = '#9181b1'

# Bright colors
[colors.bright]
black = '#513b7d'
red = '#fc737a'
green = '#b6ca68'
yellow = '#ffdd8f'
blue = '#7cacf4'
magenta = '#bcaffd'
cyan = '#f7a1e6'
white = '#d0c3ea'

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = '#9b8de2'

[[colors.indexed_colors]]
index = 17
color = '#e0d6f5'
