# -----------------------------------------------------------------------------
# Moon Queen Alacritty Colors
# Theme: Moon Queen
# Upstream: https://codeberg.org/sailorfe/moonqueen.nvim/src/branch/main/extras/alacritty/moonqueen.toml
# -----------------------------------------------------------------------------

[colors.primary]
background = '#1b1429'
foreground = '#e1d9f2'

#[colors.cursor]
#cursor = '#e1d9f2'
#text = '#1b1429'

[colors.normal]
black = '#291e3e'
red = '#d65c5c'
green = '#85d65c'
yellow = '#ebb447'
blue = '#5cadd6'
magenta = '#8f7de8'
cyan = '#db70b8'
white = '#e1d9f2'

[colors.bright]
black = '#3b2b51'
red = '#f0a8a8'
green = '#c0f0a8'
yellow = '#fadb9e'
blue = '#a8d8f0'
magenta = '#b1a3f5'
cyan = '#ec93ce'
white = '#f1ebff'
