# -----------------------------------------------------------------------------
# Moon Queen Alacritty Colors
# Theme: Moon Queen
# Upstream: https://codeberg.org/sailorfe/moonqueen.nvim/src/branch/main/extras/alacritty/moonqueen.toml
# -----------------------------------------------------------------------------

[env]
term = "xterm-256color"

[font]
normal = { family = "JetBrains Mono" }
size = 9.0

[window]
dimensions = { columns = 120, lines = 28 }

[colors]
draw_bold_text_with_bright_colors = true

# Default colors
[colors.primary]
background = '#241a37'
foreground = '#ddcdfe'

#[colors.cursor]
#cursor = '#ddcdfe'
#text = '#241a37'

# Normal colors
[colors.normal]
black = '#362753'
red = '#ef434c'
green = '#6ca522'
yellow = '#f7bb31'
blue = '#508ae2'
magenta = '#8877f8'
cyan = '#e873b9'
white = '#ddcdfe'

# Bright colors
[colors.bright]
black = '#6c4ea6'
red = '#fc737a'
green = '#b6ca68'
yellow = '#ffd470'
blue = '#7cacf4'
magenta = '#9f91fd'
cyan = '#f7a1d5'
white = '#f1ebff'

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = '#506de2'

[[colors.indexed_colors]]
index = 17
color = '#40b59e'
