# -----------------------------------------------------------------------------
# Moon Queen Alacritty Colors
# Theme: Moon Queen
# Upstream: https://codeberg.org/sailorfe/moonqueen.nvim/src/branch/main/extras/alacritty/moonqueen.toml
# -----------------------------------------------------------------------------

[colors.primary]
background = '#1b1429'
foreground = '#e1d9f2'

#[colors.cursor]
#cursor = '#e1d9f2'
#text = '#1b1429'

[colors.normal]
black = '#291e3e'
red = '#d65c5c'
green = '#add65c'
yellow = '#ebb447'
blue = '#70b8db'
magenta = '#9470db'
cyan = '#db70b8'
white = '#e1d9f2'

[colors.bright]
black = '#3b2b51'
red = '#eb8484'
green = '#c8eb84'
yellow = '#fcce73'
blue = '#93d0ed'
magenta = '#b293ed'
cyan = '#ed93d0'
white = '#f1ebff'
