[[themes]]
name = "moonqueen"
[themes.palette]
background = "#0d0a15"
foreground = "#dbd6f0"
black = "#1a142a"
blue = "#4b8fe6"
cyan = "#8566f5"
green = "#6ca522"
magenta = "#fd8bd9"
red = "#f8303a"
white = "#908aa8"
yellow = "#fbe918"
bright_black = "#271d3e"
bright_blue = "#79abec"
bright_cyan = "#ab96f8"
bright_green = "#99d945"
bright_magenta = "#febeea"
bright_red = "#f96269"
bright_white = "#dbd6f0"
bright_yellow = "#fdf27c"

[themes.component_style]
selection = { bg = "#271d3e", modifiers = ["Bold"] }
block_title = { fg = "Cyan" }
playback_track = { fg = "Magenta", modifiers = ["Bold"] }
playback_status = { fg = "White", modifiers = ["Bold"] }
playback_artists = { fg = "Blue", modifiers = ["Bold"] }
playback_album = { fg = "Red", modifiers = ["Italic"] }
playback_metadata = { fg = "White" }
playback_progress_bar = { bg = "Black", fg = "Green" }
current_playing = { fg = "Yellow", modifiers = ["Bold"] }
page_desc = { fg = "White", modifiers = ["Bold"] }
table_header = { fg = "Magenta" }
border = {}
playlist_desc = { fg = "White" }
