#-*- moonqueen

[colors]
foreground= e1d9f2
background= 1b1429
selection-background=   9470db
selection-foreground=   1b1429
urls=		70b8db
flash=		9470db

regular0=   291e3e
regular1=   d65c5c
regular2=   add65c
regular3=   ebb447
regular4=		70b8db
regular5=   9470db
regular6=   db70b8
regular7=		e1d9f2

bright0=		3b2b51
bright1=    eb8484
bright2=    c8eb84
bright3=    fcce73
bright4=    93d0ed
bright5=    b293ed
bright6=    ed93d0
bright7=    f1ebff
