#-*- moonqueen

[colors]
foreground= e1d9f2
background= 1b1429
selection-background=   8f7de8
selection-foreground=   1b1429
urls=		5cadd6
flash=		8f7de8

regular0=   291e3e
regular1=   d65c5c
regular2=   85d65c
regular3=   ebb447
regular4=		5cadd6
regular5=   8f7de8
regular6=   db70b8
regular7=		e1d9f2

bright0=		3b2b51
bright1=    f0a8a8
bright2=    c0f0a8
bright3=    fadb9e
bright4=    a8d8f0
bright5=    b1a3f5
bright6=    ec93ce
bright7=    f1ebff
