# -*- moonqueen -*-

[colors]
foreground=E1D9F2
background=1B1429
selection-background=DB70B8
selection-foreground=1B1429
urls=5CADD6
flash=DB70B8

regular0=291E3E
regular1=D65C5C
regular2=85D65C
regular3=EBB447
regular4=5CADD6
regular5=8F7DE8
regular6=DB70B8
regular7=E1D9F2

bright0=362853
bright1=F0A8A8
bright2=C0F0A8
bright3=FADB9E
bright4=A8D8F0
bright5=B1A3F5
bright6=EC93CE
bright7=F1EBFF