# -*- moonqueen tty colors -*-

if [ "$TERM" = "linux" ]; then
    echo -en "\x1b]P01B1429"
    echo -en "\x1b]P1D65C5C"
    echo -en "\x1b]P285D65C"
    echo -en "\x1b]P3EBB447"
    echo -en "\x1b]P45CADD6"
    echo -en "\x1b]P58F7DE8"
    echo -en "\x1b]P6DB70B8"
    echo -en "\x1b]P7F1EBFF"
    echo -en "\x1b]P8362853"
    echo -en "\x1b]P9F0A8A8"
    echo -en "\x1b]PAC0F0A8"
    echo -en "\x1b]PBFADB9E"
    echo -en "\x1b]PCA8D8F0"
    echo -en "\x1b]PDB1A3F5"
    echo -en "\x1b]PEEC93CE"
    echo -en "\x1b]PFE1D9F2"
    clear
fi