[colors.primary]
background = "[[base]]"
foreground = "[[text]]"

[colors.normal]
black = "[[overlay]]"
red = "[[mars]]"
green = "[[jupiter]]"
yellow = "[[venus]]"
blue = "[[mercury]]"
magenta = "[[saturn]]"
cyan = "[[moon]]"
white = "[[text]]"

[colors.bright]
black = "[[high]]"
red = "[[rei]]"
green = "[[makoto]]"
yellow = "[[minako]]"
blue = "[[ami]]"
magenta = "[[hotaru]]"
cyan = "[[usagi]]"
white = "[[light]]"
