# -*- moonqueen -*-

[colors]
foreground={{text}}
background={{base}}
selection-background={{moon}}
selection-foreground={{base}}
urls={{mercury}}
flash={{moon}}

regular0={{surface}}
regular1={{mars}}
regular2={{jupiter}}
regular3={{venus}}
regular4={{mercury}}
regular5={{saturn}}
regular6={{moon}}
regular7={{text}}

bright0={{overlay}}
bright1={{rei}}
bright2={{makoto}}
bright3={{minako}}
bright4={{ami}}
bright5={{hotaru}}
bright6={{usagi}}
bright7={{light}}
