background: [[base]]
foreground: [[text]]

color0: [[surface]]
color1: [[mars]]
color2: [[jupiter]]
color3: [[venus]]
color4: [[mercury]]
color5: [[saturn]]
color6: [[moon]]
color7: [[text]]

color8: [[overlay]]
color9: [[rei]]
color10: [[makoto]]
color11: [[minako]]
color12: [[ami]]
color13: [[hotaru]]
color14: [[usagi]]
color15: [[light]]
