if [ "$TERM" = "linux" ]; then
    echo -en "\x1b]P0{{base}}"
    echo -en "\x1b]P1{{mars}}"
    echo -en "\x1b]P2{{jupiter}}"
    echo -en "\x1b]P3{{venus}}"
    echo -en "\x1b]P4{{mercury}}"
    echo -en "\x1b]P5{{saturn}}"
    echo -en "\x1b]P6{{moon}}"
    echo -en "\x1b]P7{{text}}"
    echo -en "\x1b]P8{{overlay}}"
    echo -en "\x1b]P9{{rei}}"
    echo -en "\x1b]PA{{makoto}}"
    echo -en "\x1b]PB{{minako}}"
    echo -en "\x1b]PC{{ami}}"
    echo -en "\x1b]PD{{hotaru}}"
    echo -en "\x1b]PE{{usagi}}"
    echo -en "\x1b]PF{{light}}"
    clear
fi
