# Moon Queen for Termux
# Author: sailorfe
# Upstream: https://codeberg.org/sailorfe/moonqueen.nvim/src/branch/main/extras/termux/moonqueen.properties

background: #1B1429
foreground: #E1D9F2

color0: #291E3E
color1: #D65C5C
color2: #85D65C
color3: #EBB447
color4: #5CADD6
color5: #8F7DE8
color6: #DB70B8
color7: #E1D9F2

color8: #362853
color9: #F0A8A8
color10: #C0F0A8
color11: #FADB9E
color12: #A8D8F0
color13: #B1A3F5
color14: #EC93CE
color15: #F1EBFF
